import random


R_EATING="I dont like eating anything because I'm a bot obviously!"
R_ROBOT="Yes I am a robot, but I’m a good one. Let me prove it. How can I help you?"

R_CHAT_1= "I'm just a computer program, but I'm here to help you!"
R_CHAT_2="Once upon a time... Just kidding! I'm not much of a storyteller."
R_CHAT_3= "I don't have a favorite color, but I like chatting with you!"
R_CHAT_4= "No, I don't dream. I'm just here to assist you with your queries."
R_CHAT_5= "That's a profound question! Many people have different perspectives on the meaning of life."
R_CHAT_6="I can't sing, but I can certainly provide you with information and assistance!"
R_CHAT_7="No, I'm not a human. I'm a chatbot designed to assist you."
R_CHAT_8="I'm a computer program designed to respond to your questions and provide assistance."
R_CHAT_9= "Why don't scientists trust atoms? Because they make up everything!"
R_CHAT_10="I'm just a virtual assistant, so I don't have a physical location. I exist in the digital realm."
R_CHAT_51="I'm just a computer program, but I'm here to assist you!"
R_CHAT_52="I don't have personal preferences, but I can recommend popular movies."
R_CHAT_53="Sure! Why don't scientists trust atoms? Because they make up everything!"
R_CHAT_54="To improve your cooking skills, try experimenting with new recipes and techniques."
R_CHAT_55="As a chatbot, I don't have hobbies, but I enjoy helping users like you!"
R_CHAT_56="I don't have the capability for fun, but I'm here to provide assistance."
R_CHAT_57="Of course! How about learning the word 'serendipity'? It means finding something good without looking for it."
R_CHAT_58="That's a deep question! Many people have different perspectives on the meaning of life."
R_CHAT_59="As a chatbot, I don't have beliefs, but I'm here to provide information and assistance."
R_CHAT_60="I don't have personal preferences, but I can recommend popular books."
R_CHAT_11="I exist in the digital realm, so I don't have a physical location."
R_CHAT_12="Artificial intelligence is a fascinating field that has the potential to revolutionize many aspects of our lives."
R_CHAT_13="I'm designed to learn from interactions and provide responses based on programmed algorithms."
R_CHAT_14="Once upon a time... Just kidding! I'm not much of a storyteller."
R_CHAT_15="As a chatbot, I don't dream. I'm here to assist you with your queries."
R_CHAT_16="I'm a computer program designed to respond to your questions and provide assistance."
R_CHAT_17="I don't have the ability to eat, but I can help you find information on food."
R_CHAT_18="Did you know? Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!"
R_CHAT_19="Sure! How about a game of word association? I'll start: 'Apple'"
R_CHAT_20="I don't have personal preferences, but I can appreciate the colors of the rainbow!"
R_CHAT_21="To deal with stress, try relaxation techniques such as deep breathing, meditation, or going for a walk."
R_CHAT_22="As a chatbot, I don't have personal preferences, but I can provide information on various music genres."
R_CHAT_23="While I can't give personal advice, I can provide general information on relationships."
R_CHAT_24="As a chatbot, I don't have personal preferences, but I'm here to assist you!"
R_CHAT_25="As a chatbot, I don't have family relationships, but I'm here to help you!"
R_CHAT_26="Happiness can mean different things to different people, from enjoying small moments to achieving long-term goals."
R_CHAT_27="To handle boredom, try engaging in activities you enjoy, learning something new, or connecting with friends."
R_CHAT_28="I'm always here to assist users like you! Feel free to ask me anything."
R_CHAT_29="The best way to relax varies for each person, but activities like reading, listening to music, or practicing mindfulness can be helpful."
R_CHAT_30="Of course! Here's one: 'Success is not final, failure is not fatal: It is the courage to continue that counts.' - Winston Churchill"
R_CHAT_31="As a chatbot, I don't have personal preferences, but I can provide information on various types of food."
R_CHAT_32="The best way to start a day is by setting a positive intention and focusing on what you're grateful for."
R_CHAT_33="Philosophy is a complex subject with many different schools of thought and perspectives."
R_CHAT_34="As a chatbot, I don't experience emotions, but I'm here to assist you with your queries."
R_CHAT_35="As a chatbot, I don't have personal experiences, but I'm here to help you!"
R_CHAT_36="Love is a complex and multifaceted emotion that means different things to different people."
R_CHAT_37="To stay motivated, try setting clear goals, celebrating small victories, and finding inspiration in your passions."
R_CHAT_38="As a chatbot, I don't have personal preferences, but I can provide information on various sports."
R_CHAT_39="Space is a vast and fascinating frontier that continues to captivate scientists and explorers."
R_CHAT_40="As a chatbot, I don't have personal preferences, but I can appreciate the diversity of the animal kingdom!"
R_CHAT_41="The meaning of success varies from person to person, from achieving goals to finding fulfillment."
R_CHAT_42="As a chatbot, I don't make decisions, but I can provide information and assistance to help you make decisions."
R_CHAT_43="The best way to handle failure is to learn from it, adapt, and persevere towards your goals."
R_CHAT_44="In my 'free time,' I'm here to help users like you!"
R_CHAT_45="To deal with challenges, try breaking them down into manageable steps and seeking support from others."
R_CHAT_46="Politics is a complex and diverse field that shapes societies and governments around the world."
R_CHAT_47="To cope with stress, try practicing relaxation techniques, maintaining a healthy lifestyle, and seeking support from others."
R_CHAT_48="As a chatbot, I don't have personal preferences, but I can provide information on various destinations."
R_CHAT_49="Technology is a driving force behind innovation and progress, shaping the way we live and interact."
R_CHAT_50="To stay healthy, try maintaining a balanced diet, staying active, getting enough sleep, and managing stress."



def unknown():
    response=['could you please re-phrase that?',
                ".....",
                "Sounds about right",
                "What does that mean?"][random.randrange(4)]
    return response
